### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by nschonni** [CSSLint/csslint.net#1]
- [x] Add CNAME file
- [x] Move main branch to `gh-pages`
- [x] Set main branch in the Admin panel to `gh-pages`
- [x] Update DNS entry https://help.github.com/articles/setting-up-a-custom-domain-with-pages
- [x] ~~Make repo public~~
- [x] Profit :moneybag:

**Comment by frvge** [comment]
@stubbornella Could you please make gh-pages the default branch? My last merge went to master, so the main site isn't updated yet.

**Comment by AViscatanius** [comment]
I wished I knew what u guys was talking about lol

**Comment by nschonni** [comment]
@frvge deleted the `gh-pages` branch and recreated from the master. Swapped the `gh-pages` to the default branch and enabled the basic brach protection
